version: "3.8"

services:
  exchange-back-end:
    container_name: exchange-back-end
    image: felipewind/exchange-back-end:1.0
    ports:
      - 8090:8090
    networks:
      - fix-trading-simulator-net
    depends_on:
      - postgresql-qfj         
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql-qfj:5432/postgres?currentSchema=exchange
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUICKFIX=[default],
          [session],
          BeginString=FIX.4.4,
          SenderCompID=EXEC,
          TargetCompID=BANZAI,
          ConnectionType=acceptor,
          StartTime=00:00:00,
          EndTime=00:00:00,
          SocketAcceptPort=9880,
          ScreenLogShowHeartBeats=Y,
          JdbcStoreMessagesTableName=messages,
          JdbcStoreSessionsTableName=sessions,
          JdbcLogHeartBeats=Y,
          JdbcLogIncomingTable=messages_log_incoming,
          JdbcLogOutgoingTable=messages_log_outgoing,
          JdbcLogEventTable=event_log,
          JdbcSessionIdDefaultPropertyValue=not_null,
          AllowedRemoteAddresses=127.0.0.1\,172.0.0.2\,172.0.0.3\,broker-back-end

  broker-back-end:
    container_name: broker-back-end
    image: felipewind/broker-back-end:1.0
    ports:
      - 8080:8080
    networks:
      - fix-trading-simulator-net
    depends_on:
      - postgresql-qfj           
    environment:      
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql-qfj:5432/postgres?currentSchema=broker
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUICKFIX=[default],
          [session],
          BeginString=FIX.4.4,
          SenderCompID=BANZAI,
          TargetCompID=EXEC,
          ConnectionType=initiator,
          StartTime=00:00:00,
          EndTime=00:00:00,
          ReconnectInterval=5,
          HeartBtInt=30,
          SocketConnectHost=exchange-back-end,
          SocketConnectPort=9880,
          ScreenLogShowHeartBeats=Y,
          JdbcStoreMessagesTableName=messages,
          JdbcStoreSessionsTableName=sessions,
          JdbcLogHeartBeats=Y,
          JdbcLogIncomingTable=messages_log_incoming,
          JdbcLogOutgoingTable=messages_log_outgoing,
          JdbcLogEventTable=event_log,
          JdbcSessionIdDefaultPropertyValue=not_null          

  postgresql-qfj:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
        - 5432:5432
    networks:
      - fix-trading-simulator-net
    volumes:
      - ./init-exchange.sql:/docker-entrypoint-initdb.d/init-exchange.sql
      - ./init-broker.sql:/docker-entrypoint-initdb.d/init-broker.sql

  exchange-front-end:
    container_name: exchange-front-end
    image: felipewind/exchange-front-end:1.0
    ports:
      - 90:80
    networks:
      - fix-trading-simulator-net
    depends_on:      
      - exchange-back-end

  broker-front-end:
    container_name: broker-front-end
    image: felipewind/broker-front-end:1.0
    ports:
      - 80:80
    networks:
      - fix-trading-simulator-net
    depends_on:      
      - broker-back-end
      
networks:
  fix-trading-simulator-net:
    driver: bridge
